// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1tFu4lwzZRiLfYjmN9WlEjJJlepISz-Q',
    appId: '1:400159375770:android:729234f5539db4042d7a23',
    messagingSenderId: '400159375770',
    projectId: 'e-wallet-7c45c',
    storageBucket: 'e-wallet-7c45c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA46uBUvmVQKsSL7HIXZG58MD9jXQCFX7c',
    appId: '1:948878883710:ios:5363ad2b9fbe06b2a0512f',
    messagingSenderId: '948878883710',
    projectId: 'fir-emoney-e9256',
    storageBucket: 'fir-emoney-e9256.firebasestorage.app',
    iosBundleId: 'com.kampus.dompetKampusGlobal',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxnQSGbhmrr8lXfZRNfRLT_X43OVjxARg',
    appId: '1:400159375770:web:143db54ff42198cb2d7a23',
    messagingSenderId: '400159375770',
    projectId: 'e-wallet-7c45c',
    authDomain: 'e-wallet-7c45c.firebaseapp.com',
    storageBucket: 'e-wallet-7c45c.firebasestorage.app',
    measurementId: 'G-WX6CD4KWL1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxnQSGbhmrr8lXfZRNfRLT_X43OVjxARg',
    appId: '1:400159375770:web:2f70be4d55f8524f2d7a23',
    messagingSenderId: '400159375770',
    projectId: 'e-wallet-7c45c',
    authDomain: 'e-wallet-7c45c.firebaseapp.com',
    storageBucket: 'e-wallet-7c45c.firebasestorage.app',
    measurementId: 'G-7MXVDWX89P',
  );
}
